package com.biddingagency.domain.bid.service;

import com.biddingagency.domain.bid.entity.BidRequest;
import com.biddingagency.domain.bid.entity.ClientDocument;
import com.biddingagency.domain.bid.repository.ClientDocumentRepository;
import com.biddingagency.domain.document.entity.BidDocument;
import com.biddingagency.domain.document.entity.DocumentType;
import com.biddingagency.domain.document.service.BidDocumentService;
import com.biddingagency.domain.document.service.DocumentVersionService;
import com.biddingagency.domain.notice.repository.NoticeRepository;
import com.biddingagency.domain.proposal.entity.GenerationTargetType;
import com.biddingagency.domain.proposal.entity.ProposalSection;
import com.biddingagency.domain.proposal.entity.VerificationLog;
import com.biddingagency.domain.proposal.entity.VerificationTargetType;
import com.biddingagency.domain.proposal.entity.Verdict;
import com.biddingagency.domain.proposal.service.GenerationLogService;
import com.biddingagency.domain.proposal.service.ProposalService;
import com.biddingagency.domain.proposal.service.VerificationLogService;
import com.biddingagency.domain.opportunity.entity.Opportunity;
import com.biddingagency.domain.opportunity.entity.OpportunityRequirementItem;
import com.biddingagency.domain.opportunity.entity.OpportunityVisibility;
import com.biddingagency.domain.opportunity.entity.RequirementCategory;
import com.biddingagency.domain.opportunity.repository.OpportunityRequirementItemRepository;
import com.biddingagency.domain.rfp.entity.IndustryType;
import com.biddingagency.domain.rfp.repository.PatternGuideRepository;
import com.biddingagency.domain.rfp.service.ReferenceSampleService;
import com.biddingagency.integration.ai.client.dto.*;
import com.biddingagency.integration.llmplatform.LLMPlatformClient;
import com.biddingagency.integration.llmplatform.LLMPlatformException;
import com.biddingagency.integration.llmplatform.dto.WorkflowRunResponse;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;
import java.util.stream.Collectors;

/**
 * LLM Platform 워크플로우 비동기 실행 서비스
 *
 * BidFSMService에서 상태 전환 후 호출됩니다.
 * - REQUIREMENT_ANALYSIS 진입 → 요구사항 자동 추출
 * - DOCUMENT_DRAFTING 진입    → 문서 자동 생성
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class AIWorkflowService {

    private final LLMPlatformClient llmPlatformClient;
    private final OpportunityRequirementItemRepository requirementItemRepository;
    private final NoticeRepository noticeRepository;
    private final ClientDocumentRepository clientDocumentRepository;
    private final PatternGuideRepository patternGuideRepository;
    private final ReferenceSampleService referenceSampleService;
    // CR-028: 제안서 파이프라인 3단계
    private final BidDocumentService bidDocumentService;
    private final DocumentVersionService documentVersionService;
    private final ProposalService proposalService;
    // CR-029: 단계별 비용 추적
    private final GenerationLogService generationLogService;
    // CR-031: 충실성·분량 검증
    private final VerificationLogService verificationLogService;

    /** DOCUMENT_DRAFTING 진입 시 자동 생성할 문서 타입 목록 */
    @Value("${app.ai.auto-generate-document-types:COVER_LETTER,TECHNICAL_PROPOSAL}")
    private String autoGenerateDocumentTypes;

    // ─────────────────────────────────────────────────────────────────────────
    // 요구사항 추출 (REQUIREMENT_ANALYSIS 진입 시)
    // ─────────────────────────────────────────────────────────────────────────

    @Async("llmTaskExecutor")
    public void extractRequirementsAsync(BidRequest bidRequest) {
        UUID bidRequestId = bidRequest.getId();
        Opportunity opp = bidRequest.getOpportunity();
        log.info("[AI] 요구사항 추출 시작: bidRequestId={}, opportunityId={}", bidRequestId, opp.getId());

        try {
            RequirementExtractionRequest request = RequirementExtractionRequest.builder()
                .opportunityId(opp.getId())
                .opportunityText(buildOpportunityText(opp))
                .metadata(Map.of("bidRequestId", bidRequestId.toString()))
                .build();

            RequirementExtractionResponse response = llmPlatformClient.extractRequirements(request);

            if (!"success".equalsIgnoreCase(response.getStatus())) {
                log.error("[AI] 요구사항 추출 실패: bidRequestId={}, error={}", bidRequestId, response.getErrorMessage());
                return;
            }

            // CR-002: Aimbase 워크플로우가 MCP save_requirements를 직접 호출하여 DB에 저장.
            // saveExtractedRequirements() 호출 불필요.
            log.info("[AI] 요구사항 추출 완료 (Aimbase MCP 콜백으로 저장됨): bidRequestId={}", bidRequestId);

        } catch (LLMPlatformException e) {
            log.error("[AI] Aimbase 오류 (요구사항 추출): bidRequestId={}", bidRequestId, e);
        } catch (Exception e) {
            log.error("[AI] 예상치 못한 오류 (요구사항 추출): bidRequestId={}", bidRequestId, e);
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 문서 생성 (DOCUMENT_DRAFTING 진입 시)
    // ─────────────────────────────────────────────────────────────────────────

    /** MCP 콜백과 동일한 시스템 편집자 UUID. */
    private static final UUID SYSTEM_EDITOR = new UUID(0L, 0L);

    /**
     * CR-028: 제안서 파이프라인 3단계 (design → write-section → assemble).
     * DOCUMENT_DRAFTING 진입 시 자동 생성할 문서 타입마다 전체 파이프라인을 순차 실행.
     * 각 단계 결과는 Aimbase MCP 콜백으로 DB 에 저장되고, BE 는 다음 단계 입력을 DB 에서 읽어 잇는다.
     */
    @Async("llmTaskExecutor")
    public void generateDocumentsAsync(BidRequest bidRequest) {
        UUID bidRequestId = bidRequest.getId();
        Opportunity opp = bidRequest.getOpportunity();
        log.info("[AI] 제안서 파이프라인 시작: bidRequestId={}, opportunityId={}", bidRequestId, opp.getId());

        List<DocumentType> documentTypes = parseDocumentTypes(autoGenerateDocumentTypes);

        for (DocumentType documentType : documentTypes) {
            try {
                runProposalPipeline(bidRequest, documentType);
            } catch (Exception e) {
                log.error("[AI] 제안서 파이프라인 실패: bidRequestId={}, documentType={}", bidRequestId, documentType, e);
            }
        }

        log.info("[AI] 제안서 파이프라인 완료: bidRequestId={}, 문서={}종", bidRequestId, documentTypes.size());
    }

    /**
     * 단일 documentType 에 대한 design → write-section(전 section) → assemble 파이프라인.
     * 동기 실행(폴링) — 호출부에서 @Async 로 감싼다.
     */
    private void runProposalPipeline(BidRequest bidRequest, DocumentType documentType) {
        UUID bidRequestId = bidRequest.getId();
        Opportunity opp = bidRequest.getOpportunity();

        // 0. 빈 BidDocument 확보 (design 입력 documentId)
        UUID documentId = ensureDocument(bidRequestId, documentType);

        // 1. design — chapter/section 트리 생성 (Aimbase 가 save_proposal_structure 콜백)
        Map<String, Object> designInput = new HashMap<>();
        designInput.put("documentId", documentId.toString());
        designInput.put("bidRequestId", bidRequestId.toString());
        designInput.put("documentType", documentType.name());
        designInput.put("opportunityText", buildOpportunityText(opp));
        WorkflowRunResponse designRun = llmPlatformClient.runProposalDesign(designInput);
        logGeneration(GenerationTargetType.DESIGN, documentId, designRun);

        // 2. write-section — 저장된 section 마다 본문 작성 (section 1개 = WF 1회)
        List<ProposalSection> sections = proposalService.getAllSections(documentId);
        log.info("[AI] design 완료: documentId={}, sections={}건", documentId, sections.size());
        if (sections.isEmpty()) {
            log.warn("[AI] design 이 section 을 만들지 못함 — write/assemble 스킵: documentId={}", documentId);
            return;
        }
        for (ProposalSection section : sections) {
            try {
                writeSection(section.getId());
            } catch (Exception e) {
                log.error("[AI] write-section 실패(계속 진행): sectionId={}", section.getId(), e);
            }
        }

        // 3. assemble — 트리 전체를 합쳐 통합 contentJson 저장 (Aimbase 가 save_document_version 콜백)
        Map<String, Object> assembleInput = new HashMap<>();
        assembleInput.put("documentId", documentId.toString());
        assembleInput.put("bidRequestId", bidRequestId.toString());
        assembleInput.put("documentType", documentType.name());
        WorkflowRunResponse assembleRun = llmPlatformClient.runProposalAssemble(assembleInput);
        logGeneration(GenerationTargetType.ASSEMBLE, documentId, assembleRun);

        log.info("[AI] 제안서 파이프라인 완료: documentId={}, documentType={}", documentId, documentType);
    }

    /**
     * CR-028/CR-030: section 1개 본문 재작성 (write-section WF 호출).
     * 관리자 콘솔 "이 섹션만 다시" 버튼이 호출. LOCKED 검증은 save_section_blocks 콜백 시점에서 강제.
     */
    @Async("llmTaskExecutor")
    public void writeSectionAsync(UUID sectionId) {
        log.info("[AI] 개별 section 재작성 시작: sectionId={}", sectionId);
        try {
            writeSection(sectionId);
        } catch (Exception e) {
            log.error("[AI] 개별 section 재작성 실패: sectionId={}", sectionId, e);
        }
    }

    /**
     * write-section WF 동기 호출 (Aimbase 가 get_section_context → save_section_blocks 콜백).
     * save_section_blocks 콜백 시점에 ProposalService.replaceBlocks 가 BE 정형 룰(RULE) 을 적재한다.
     * 이어서 CR-031 LLM 충실성 검증을 1회 돌리고, FAIL 이면 1회만 자동 재작성+재검증한다.
     */
    private void writeSection(UUID sectionId) {
        proposalService.markDrafting(sectionId);
        Map<String, Object> input = new HashMap<>();
        input.put("sectionId", sectionId.toString());
        WorkflowRunResponse run = llmPlatformClient.runWriteSection(input);
        logGeneration(GenerationTargetType.WRITE_SECTION, sectionId, run);

        // CR-031: 충실성 검증 + 1회 자동 재시도
        verifySectionWithRetry(sectionId);
    }

    /**
     * CR-031: section 충실성 검증 (verify-fidelity WF). 환각 ≥1(FAIL) 이면 1회만 자동 재작성 후 재검증.
     * 2회째도 FAIL 이면 NEEDS_REGEN 으로 두고 사람을 호출한다(자동 재시도 종료).
     * verify-fidelity WF 가 MCP save_verification_result 로 verification_log 를 직접 저장하므로,
     * BE 는 WF 완료 후 최신 LLM 검증 결과를 읽어 PASS/FAIL 분기만 한다.
     */
    /**
     * CR-031: 관리자 수동 재검증 — section 본문을 재작성하지 않고 충실성 검증만 1회 재실행.
     * "재생성"(writeSectionAsync) 과 분리 — 본문은 그대로 두고 검증 결과만 갱신.
     */
    @Async("llmTaskExecutor")
    public void verifySectionAsync(UUID sectionId) {
        log.info("[CR-031] 수동 재검증 시작: sectionId={}", sectionId);
        Verdict verdict = runVerifyFidelity(sectionId);
        if (verdict == Verdict.FAIL) {
            proposalService.markNeedsRegen(sectionId);
        }
    }

    private void verifySectionWithRetry(UUID sectionId) {
        Verdict verdict = runVerifyFidelity(sectionId);
        if (verdict == Verdict.FAIL) {
            log.warn("[CR-031] section 충실성 FAIL — 1회 자동 재작성: sectionId={}", sectionId);
            // 환각 목록을 negative example 로 다음 write-section 입력에 실어 재작성
            List<Map<String, Object>> halls = latestHallucinations(sectionId);
            Map<String, Object> retryInput = new HashMap<>();
            retryInput.put("sectionId", sectionId.toString());
            retryInput.put("avoidHallucinations", halls);
            proposalService.markDrafting(sectionId);
            WorkflowRunResponse retryRun = llmPlatformClient.runWriteSection(retryInput);
            logGeneration(GenerationTargetType.WRITE_SECTION, sectionId, retryRun);

            Verdict retryVerdict = runVerifyFidelity(sectionId);
            if (retryVerdict == Verdict.FAIL) {
                log.warn("[CR-031] 재작성 후도 FAIL — NEEDS_REGEN(사람 호출): sectionId={}", sectionId);
                proposalService.markNeedsRegen(sectionId);
            }
        }
    }

    /**
     * verify-fidelity WF 1회 실행 후 최신 LLM 검증 결과의 verdict 반환.
     * WF/검증 자체 실패 시 보수적으로 FAIL 로 간주하지 않고 PASS 폴백 — 검증 부재로 파이프라인을 막지 않는다.
     */
    private Verdict runVerifyFidelity(UUID sectionId) {
        try {
            int attempt = verificationLogService.nextAttempt(VerificationTargetType.PROPOSAL_SECTION, sectionId);
            Map<String, Object> input = new HashMap<>();
            input.put("targetType", VerificationTargetType.PROPOSAL_SECTION.name());
            input.put("targetId", sectionId.toString());
            input.put("attempt", attempt);
            WorkflowRunResponse run = llmPlatformClient.runVerifyFidelity(input);
            logGeneration(GenerationTargetType.VERIFY, sectionId, run);

            // 최신 LLM 검증 결과 (WF 가 save_verification_result 콜백으로 이미 저장)
            return verificationLogService.findLatest(VerificationTargetType.PROPOSAL_SECTION, sectionId)
                    .filter(v -> v.getMethod() == com.biddingagency.domain.proposal.entity.VerificationMethod.LLM)
                    .map(VerificationLog::getVerdict)
                    .orElse(Verdict.PASS);
        } catch (Exception e) {
            log.warn("[CR-031] section 충실성 검증 실패(PASS 폴백): sectionId={}", sectionId, e);
            return Verdict.PASS;
        }
    }

    private List<Map<String, Object>> latestHallucinations(UUID sectionId) {
        return verificationLogService.findLatest(VerificationTargetType.PROPOSAL_SECTION, sectionId)
                .map(VerificationLog::getHallucinations)
                .orElse(List.of());
    }

    /**
     * CR-029 — 단계 1회 결과를 generation_log 에 적재. 비용 추적용 보조 작업이므로
     * 실패해도 본 파이프라인을 막지 않는다(append-only, best-effort).
     * 모델은 워크플로우 connection 에서 실측 조회(캐싱) — 정책 추정 아님.
     */
    private void logGeneration(GenerationTargetType stage, UUID targetId, WorkflowRunResponse run) {
        try {
            String model = switch (stage) {
                case DESIGN -> llmPlatformClient.resolveDesignModel();
                case WRITE_SECTION -> llmPlatformClient.resolveWriteSectionModel();
                case ASSEMBLE -> llmPlatformClient.resolveAssembleModel();
                case VERIFY -> llmPlatformClient.resolveVerifyModel();
                default -> null;
            };
            generationLogService.recordStage(stage, targetId, run, model);
        } catch (Exception e) {
            log.warn("[CR-029] generation_log 적재 실패(무시): stage={}, target={}", stage, targetId, e);
        }
    }

    /** 빈 BidDocument 확보 — 이미 있으면 재사용, 없으면 빈 본문으로 생성. */
    private UUID ensureDocument(UUID bidRequestId, DocumentType documentType) {
        try {
            BidDocument existing = bidDocumentService.findByBidRequestAndType(bidRequestId, documentType);
            return existing.getId();
        } catch (Exception e) {
            BidDocument created = documentVersionService.createDocument(
                    bidRequestId, documentType, Map.of(), SYSTEM_EDITOR);
            log.info("[AI] design 용 빈 문서 생성: documentId={}, type={}", created.getId(), documentType);
            return created.getId();
        }
    }

    /**
     * CR-017 ②: 개별 문서 타입 1건만 재생성 (전체 재생성과 분리).
     * REVIEW 상태에서 관리자가 특정 문서만 다시 생성. 결과는 새 버전으로 누적(Aimbase MCP save_document_version 콜백).
     * 상태/LOCKED 검증은 호출부(컨트롤러)에서 선행.
     */
    @Async("llmTaskExecutor")
    public void regenerateSingleDocumentAsync(BidRequest bidRequest, DocumentType documentType) {
        Opportunity opp = bidRequest.getOpportunity();
        log.info("[AI] 개별 문서 재생성 시작: bidRequestId={}, documentType={}", bidRequest.getId(), documentType);

        List<RequirementDTO> requirements = loadRequirementsAsDto(opp.getId());
        generateSingleDocument(bidRequest, opp, documentType, requirements);

        log.info("[AI] 개별 문서 재생성 완료(요청 발행): bidRequestId={}, documentType={}", bidRequest.getId(), documentType);
    }

    @Transactional
    protected void generateSingleDocument(BidRequest bidRequest, Opportunity opp,
                                          DocumentType documentType, List<RequirementDTO> requirements) {
        UUID bidRequestId = bidRequest.getId();
        log.info("[AI] {} 문서 생성 중: bidRequestId={}", documentType, bidRequestId);

        try {
            // CR-003: 3파이프라인 context 조합
            Map<String, Object> context = build3PipelineContext(bidRequest, opp);

            DocumentGenerationRequest request = DocumentGenerationRequest.builder()
                .bidRequestId(bidRequestId)
                .documentType(documentType.name())
                .opportunityText(buildOpportunityText(opp))
                .requirements(requirements)
                .context(context)
                .build();

            DocumentGenerationResponse response = llmPlatformClient.generateDocument(request);

            if (!"success".equalsIgnoreCase(response.getStatus())) {
                log.error("[AI] {} 문서 생성 실패: bidRequestId={}, error={}", documentType, bidRequestId, response.getErrorMessage());
                return;
            }

            // CR-002: Aimbase 워크플로우가 MCP save_document_version을 직접 호출하여 DB에 저장.
            // documentVersionService.createDocument() 호출 불필요.
            log.info("[AI] {} 문서 생성 완료 (Aimbase MCP 콜백으로 저장됨): bidRequestId={}", documentType, bidRequestId);

        } catch (LLMPlatformException e) {
            log.error("[AI] Aimbase 오류 ({} 생성): bidRequestId={}", documentType, bidRequestId, e);
        } catch (Exception e) {
            log.error("[AI] 예상치 못한 오류 ({} 생성): bidRequestId={}", documentType, bidRequestId, e);
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 내부 유틸
    // ─────────────────────────────────────────────────────────────────────────

    @Transactional
    protected void saveExtractedRequirements(Opportunity opportunity, List<RequirementItem> items) {
        if (items == null || items.isEmpty()) return;

        requirementItemRepository.deleteByOpportunityId(opportunity.getId());

        List<OpportunityRequirementItem> entities = items.stream().map(item -> {
            RequirementCategory category;
            try {
                category = RequirementCategory.valueOf(item.getCategory().toUpperCase());
            } catch (Exception e) {
                category = RequirementCategory.OTHER;
            }

            String title = item.getTitle();
            if (title != null && title.length() > 500) title = title.substring(0, 500);

            return OpportunityRequirementItem.builder()
                .opportunity(opportunity)
                .category(category)
                .title(title != null ? title : "(제목 없음)")
                .description(item.getDescription())
                .isBlocker(item.isBlocker())
                .requirementJson(item.getMetadata() != null ? item.getMetadata() : Map.of())
                .build();
        }).collect(Collectors.toList());

        requirementItemRepository.saveAll(entities);
    }

    /**
     * CR-003: 3파이프라인 context 조합
     * ①공고 사전 분석 캐시 + ②사용자 제출 서류 + ③과거 제출 이력
     * 조건 분기 없음 — 조회해서 넘기면 끝. 비어있으면 빈 배열/null.
     */
    private Map<String, Object> build3PipelineContext(BidRequest bidRequest, Opportunity opp) {
        Map<String, Object> context = new HashMap<>();
        context.put("opportunityId", opp.getId().toString());
        context.put("organizationName", opp.getOrganizationName() != null ? opp.getOrganizationName() : "");

        // Pipeline 1: 공고문(Notice) 한글화/요약 결과 — 노출 중인 공고문 중 최신 1건 (CR-016)
        noticeRepository.findFirstByOpportunityIdAndVisibilityOrderByAnalyzedAtDesc(
                opp.getId(), OpportunityVisibility.VISIBLE)
            .filter(n -> n.isGenerationCompleted())
            .ifPresent(notice -> context.put("opportunityAnalysis", Map.of(
                "summary", notice.getSummaryJson() != null ? notice.getSummaryJson() : Map.of(),
                "documentFormats", notice.getDocumentFormatsJson() != null ? notice.getDocumentFormatsJson() : Map.of(),
                "requiredDocuments", notice.getRequiredDocumentsJson() != null ? notice.getRequiredDocumentsJson() : Map.of(),
                "llmPromptPreset", notice.getLlmPromptPresetJson() != null ? notice.getLlmPromptPresetJson() : Map.of()
            )));

        // Pipeline 2: 사용자 제출 서류
        List<ClientDocument> clientDocs = clientDocumentRepository.findByBidRequestId(bidRequest.getId());
        context.put("clientDocuments", clientDocs.stream().map(cd -> Map.of(
            "fileName", cd.getFileName(),
            "category", cd.getDocumentCategory() != null ? cd.getDocumentCategory() : "",
            "storageUrl", cd.getStorageUrl() != null ? cd.getStorageUrl() : ""
        )).toList());

        // Pipeline 3 (CR-014): 성공 제안서 자산 — 신규 공고 유형으로 매칭.
        // 기존 "사용자 본인 과거 이력"을 대체. ⓐ공고유형 가이드(어떻게 쓸지) + ⓑ성공 원본 메타(이렇게 썼다).
        // industry_type=null(미분류)이면 빈 처리. 원본은 형식·전략 참고용, 사실 복붙 금지(BIZ-019).
        IndustryType industryType = opp.getIndustryType();
        Map<String, Object> successGuide = (industryType == null) ? null
                : patternGuideRepository.findByIndustryType(industryType)
                    .map(guide -> guide.getGuideJson())
                    .orElse(null);
        context.put("successGuide", successGuide);
        context.put("referenceSamples", referenceSampleService.collect(industryType));
        context.put("referenceUsagePolicy",
                "성공 제안서 원본은 형식·구성·전략 참고용입니다. 회사명·실적·수치 등 사실(fact)은 "
                + "사용자 제출 정보(clientDocuments)에서만 가져오세요. 원본의 사실을 그대로 복사하지 마세요(교차오염 방지).");

        return context;
    }

    private List<RequirementDTO> loadRequirementsAsDto(UUID opportunityId) {
        return requirementItemRepository.findByOpportunityId(opportunityId).stream()
            .map(req -> RequirementDTO.builder()
                .id(req.getId())
                .category(req.getCategory().name())
                .title(req.getTitle())
                .description(req.getDescription())
                .isBlocker(Boolean.TRUE.equals(req.getIsBlocker()))
                .metadata(req.getRequirementJson())
                .build())
            .collect(Collectors.toList());
    }

    private String buildOpportunityText(Opportunity opp) {
        StringBuilder sb = new StringBuilder();
        sb.append("공고 제목: ").append(opp.getTitle()).append("\n");
        if (opp.getOrganizationName() != null)
            sb.append("기관: ").append(opp.getOrganizationName()).append("\n");
        if (opp.getType() != null)
            sb.append("유형: ").append(opp.getType()).append("\n");
        if (opp.getResponseDeadline() != null)
            sb.append("마감일: ").append(opp.getResponseDeadline()).append("\n");
        if (opp.getSolicitationNumber() != null)
            sb.append("공고번호: ").append(opp.getSolicitationNumber()).append("\n");
        if (opp.getUiLink() != null)
            sb.append("링크: ").append(opp.getUiLink()).append("\n");

        // rawJson에서 추가 정보 추출
        if (opp.getRawJson() != null && !opp.getRawJson().isEmpty()) {
            Object description = opp.getRawJson().get("description");
            if (description != null) {
                sb.append("\n상세 설명:\n").append(description);
            }
        }
        return sb.toString();
    }

    private List<DocumentType> parseDocumentTypes(String typesConfig) {
        return Arrays.stream(typesConfig.split(","))
            .map(String::trim)
            .map(s -> {
                try { return DocumentType.valueOf(s.toUpperCase()); }
                catch (Exception e) { return null; }
            })
            .filter(Objects::nonNull)
            .collect(Collectors.toList());
    }
}
