package com.biddingagency.domain.bid.service;

import com.biddingagency.domain.bid.entity.BidRequest;
import com.biddingagency.domain.bid.entity.ClientDocument;
import com.biddingagency.domain.bid.repository.ClientDocumentRepository;
import com.biddingagency.domain.document.entity.DocumentType;
import com.biddingagency.domain.opportunity.entity.AnalysisStatus;
import com.biddingagency.domain.opportunity.entity.Opportunity;
import com.biddingagency.domain.opportunity.entity.OpportunityRequirementItem;
import com.biddingagency.domain.opportunity.entity.RequirementCategory;
import com.biddingagency.domain.opportunity.repository.OpportunityAnalysisRepository;
import com.biddingagency.domain.opportunity.repository.OpportunityRequirementItemRepository;
import com.biddingagency.domain.rfp.entity.IndustryType;
import com.biddingagency.domain.rfp.repository.PatternGuideRepository;
import com.biddingagency.domain.rfp.service.ReferenceSampleService;
import com.biddingagency.integration.ai.client.dto.*;
import com.biddingagency.integration.llmplatform.LLMPlatformClient;
import com.biddingagency.integration.llmplatform.LLMPlatformException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Async;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.*;
import java.util.stream.Collectors;

/**
 * LLM Platform 워크플로우 비동기 실행 서비스
 *
 * BidFSMService에서 상태 전환 후 호출됩니다.
 * - REQUIREMENT_ANALYSIS 진입 → 요구사항 자동 추출
 * - DOCUMENT_DRAFTING 진입    → 문서 자동 생성
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class AIWorkflowService {

    private final LLMPlatformClient llmPlatformClient;
    private final OpportunityRequirementItemRepository requirementItemRepository;
    private final OpportunityAnalysisRepository opportunityAnalysisRepository;
    private final ClientDocumentRepository clientDocumentRepository;
    private final PatternGuideRepository patternGuideRepository;
    private final ReferenceSampleService referenceSampleService;

    /** DOCUMENT_DRAFTING 진입 시 자동 생성할 문서 타입 목록 */
    @Value("${app.ai.auto-generate-document-types:COVER_LETTER,TECHNICAL_PROPOSAL}")
    private String autoGenerateDocumentTypes;

    // ─────────────────────────────────────────────────────────────────────────
    // 요구사항 추출 (REQUIREMENT_ANALYSIS 진입 시)
    // ─────────────────────────────────────────────────────────────────────────

    @Async("llmTaskExecutor")
    public void extractRequirementsAsync(BidRequest bidRequest) {
        UUID bidRequestId = bidRequest.getId();
        Opportunity opp = bidRequest.getOpportunity();
        log.info("[AI] 요구사항 추출 시작: bidRequestId={}, opportunityId={}", bidRequestId, opp.getId());

        try {
            RequirementExtractionRequest request = RequirementExtractionRequest.builder()
                .opportunityId(opp.getId())
                .opportunityText(buildOpportunityText(opp))
                .metadata(Map.of("bidRequestId", bidRequestId.toString()))
                .build();

            RequirementExtractionResponse response = llmPlatformClient.extractRequirements(request);

            if (!"success".equalsIgnoreCase(response.getStatus())) {
                log.error("[AI] 요구사항 추출 실패: bidRequestId={}, error={}", bidRequestId, response.getErrorMessage());
                return;
            }

            // CR-002: Aimbase 워크플로우가 MCP save_requirements를 직접 호출하여 DB에 저장.
            // saveExtractedRequirements() 호출 불필요.
            log.info("[AI] 요구사항 추출 완료 (Aimbase MCP 콜백으로 저장됨): bidRequestId={}", bidRequestId);

        } catch (LLMPlatformException e) {
            log.error("[AI] Aimbase 오류 (요구사항 추출): bidRequestId={}", bidRequestId, e);
        } catch (Exception e) {
            log.error("[AI] 예상치 못한 오류 (요구사항 추출): bidRequestId={}", bidRequestId, e);
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 문서 생성 (DOCUMENT_DRAFTING 진입 시)
    // ─────────────────────────────────────────────────────────────────────────

    @Async("llmTaskExecutor")
    public void generateDocumentsAsync(BidRequest bidRequest) {
        UUID bidRequestId = bidRequest.getId();
        Opportunity opp = bidRequest.getOpportunity();
        log.info("[AI] 문서 생성 시작: bidRequestId={}, opportunityId={}", bidRequestId, opp.getId());

        // DB에서 이미 추출된 요구사항 로드
        List<RequirementDTO> requirements = loadRequirementsAsDto(opp.getId());

        // 자동 생성할 문서 타입 파싱
        List<DocumentType> documentTypes = parseDocumentTypes(autoGenerateDocumentTypes);

        for (DocumentType documentType : documentTypes) {
            generateSingleDocument(bidRequest, opp, documentType, requirements);
        }

        log.info("[AI] 문서 생성 완료: bidRequestId={}, 생성={}종", bidRequestId, documentTypes.size());
    }

    @Transactional
    protected void generateSingleDocument(BidRequest bidRequest, Opportunity opp,
                                          DocumentType documentType, List<RequirementDTO> requirements) {
        UUID bidRequestId = bidRequest.getId();
        log.info("[AI] {} 문서 생성 중: bidRequestId={}", documentType, bidRequestId);

        try {
            // CR-003: 3파이프라인 context 조합
            Map<String, Object> context = build3PipelineContext(bidRequest, opp);

            DocumentGenerationRequest request = DocumentGenerationRequest.builder()
                .bidRequestId(bidRequestId)
                .documentType(documentType.name())
                .opportunityText(buildOpportunityText(opp))
                .requirements(requirements)
                .context(context)
                .build();

            DocumentGenerationResponse response = llmPlatformClient.generateDocument(request);

            if (!"success".equalsIgnoreCase(response.getStatus())) {
                log.error("[AI] {} 문서 생성 실패: bidRequestId={}, error={}", documentType, bidRequestId, response.getErrorMessage());
                return;
            }

            // CR-002: Aimbase 워크플로우가 MCP save_document_version을 직접 호출하여 DB에 저장.
            // documentVersionService.createDocument() 호출 불필요.
            log.info("[AI] {} 문서 생성 완료 (Aimbase MCP 콜백으로 저장됨): bidRequestId={}", documentType, bidRequestId);

        } catch (LLMPlatformException e) {
            log.error("[AI] Aimbase 오류 ({} 생성): bidRequestId={}", documentType, bidRequestId, e);
        } catch (Exception e) {
            log.error("[AI] 예상치 못한 오류 ({} 생성): bidRequestId={}", documentType, bidRequestId, e);
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // 내부 유틸
    // ─────────────────────────────────────────────────────────────────────────

    @Transactional
    protected void saveExtractedRequirements(Opportunity opportunity, List<RequirementItem> items) {
        if (items == null || items.isEmpty()) return;

        requirementItemRepository.deleteByOpportunityId(opportunity.getId());

        List<OpportunityRequirementItem> entities = items.stream().map(item -> {
            RequirementCategory category;
            try {
                category = RequirementCategory.valueOf(item.getCategory().toUpperCase());
            } catch (Exception e) {
                category = RequirementCategory.OTHER;
            }

            String title = item.getTitle();
            if (title != null && title.length() > 500) title = title.substring(0, 500);

            return OpportunityRequirementItem.builder()
                .opportunity(opportunity)
                .category(category)
                .title(title != null ? title : "(제목 없음)")
                .description(item.getDescription())
                .isBlocker(item.isBlocker())
                .requirementJson(item.getMetadata() != null ? item.getMetadata() : Map.of())
                .build();
        }).collect(Collectors.toList());

        requirementItemRepository.saveAll(entities);
    }

    /**
     * CR-003: 3파이프라인 context 조합
     * ①공고 사전 분석 캐시 + ②사용자 제출 서류 + ③과거 제출 이력
     * 조건 분기 없음 — 조회해서 넘기면 끝. 비어있으면 빈 배열/null.
     */
    private Map<String, Object> build3PipelineContext(BidRequest bidRequest, Opportunity opp) {
        Map<String, Object> context = new HashMap<>();
        context.put("opportunityId", opp.getId().toString());
        context.put("organizationName", opp.getOrganizationName() != null ? opp.getOrganizationName() : "");

        // Pipeline 1: 공고 사전 분석 결과 (캐시)
        opportunityAnalysisRepository.findByOpportunityId(opp.getId())
            .filter(a -> a.getStatus() == AnalysisStatus.COMPLETED)
            .ifPresent(analysis -> context.put("opportunityAnalysis", Map.of(
                "summary", analysis.getSummaryJson() != null ? analysis.getSummaryJson() : Map.of(),
                "documentFormats", analysis.getDocumentFormatsJson() != null ? analysis.getDocumentFormatsJson() : Map.of(),
                "requiredDocuments", analysis.getRequiredDocumentsJson() != null ? analysis.getRequiredDocumentsJson() : Map.of(),
                "llmPromptPreset", analysis.getLlmPromptPresetJson() != null ? analysis.getLlmPromptPresetJson() : Map.of()
            )));

        // Pipeline 2: 사용자 제출 서류
        List<ClientDocument> clientDocs = clientDocumentRepository.findByBidRequestId(bidRequest.getId());
        context.put("clientDocuments", clientDocs.stream().map(cd -> Map.of(
            "fileName", cd.getFileName(),
            "category", cd.getDocumentCategory() != null ? cd.getDocumentCategory() : "",
            "storageUrl", cd.getStorageUrl() != null ? cd.getStorageUrl() : ""
        )).toList());

        // Pipeline 3 (CR-014): 성공 제안서 자산 — 신규 공고 유형으로 매칭.
        // 기존 "사용자 본인 과거 이력"을 대체. ⓐ공고유형 가이드(어떻게 쓸지) + ⓑ성공 원본 메타(이렇게 썼다).
        // industry_type=null(미분류)이면 빈 처리. 원본은 형식·전략 참고용, 사실 복붙 금지(BIZ-019).
        IndustryType industryType = opp.getIndustryType();
        Map<String, Object> successGuide = (industryType == null) ? null
                : patternGuideRepository.findByIndustryType(industryType)
                    .map(guide -> guide.getGuideJson())
                    .orElse(null);
        context.put("successGuide", successGuide);
        context.put("referenceSamples", referenceSampleService.collect(industryType));
        context.put("referenceUsagePolicy",
                "성공 제안서 원본은 형식·구성·전략 참고용입니다. 회사명·실적·수치 등 사실(fact)은 "
                + "사용자 제출 정보(clientDocuments)에서만 가져오세요. 원본의 사실을 그대로 복사하지 마세요(교차오염 방지).");

        return context;
    }

    private List<RequirementDTO> loadRequirementsAsDto(UUID opportunityId) {
        return requirementItemRepository.findByOpportunityId(opportunityId).stream()
            .map(req -> RequirementDTO.builder()
                .id(req.getId())
                .category(req.getCategory().name())
                .title(req.getTitle())
                .description(req.getDescription())
                .isBlocker(Boolean.TRUE.equals(req.getIsBlocker()))
                .metadata(req.getRequirementJson())
                .build())
            .collect(Collectors.toList());
    }

    private String buildOpportunityText(Opportunity opp) {
        StringBuilder sb = new StringBuilder();
        sb.append("공고 제목: ").append(opp.getTitle()).append("\n");
        if (opp.getOrganizationName() != null)
            sb.append("기관: ").append(opp.getOrganizationName()).append("\n");
        if (opp.getType() != null)
            sb.append("유형: ").append(opp.getType()).append("\n");
        if (opp.getResponseDeadline() != null)
            sb.append("마감일: ").append(opp.getResponseDeadline()).append("\n");
        if (opp.getSolicitationNumber() != null)
            sb.append("공고번호: ").append(opp.getSolicitationNumber()).append("\n");
        if (opp.getUiLink() != null)
            sb.append("링크: ").append(opp.getUiLink()).append("\n");

        // rawJson에서 추가 정보 추출
        if (opp.getRawJson() != null && !opp.getRawJson().isEmpty()) {
            Object description = opp.getRawJson().get("description");
            if (description != null) {
                sb.append("\n상세 설명:\n").append(description);
            }
        }
        return sb.toString();
    }

    private List<DocumentType> parseDocumentTypes(String typesConfig) {
        return Arrays.stream(typesConfig.split(","))
            .map(String::trim)
            .map(s -> {
                try { return DocumentType.valueOf(s.toUpperCase()); }
                catch (Exception e) { return null; }
            })
            .filter(Objects::nonNull)
            .collect(Collectors.toList());
    }
}
